var textures = [{
  "path": "/demos/assets/skittles/skittles2.png",
  "name": "skittles"
}, {
  "path": "/demos/assets/skittles/ground.png",
  "name": "ground"
}, {
  "path": "/demos/assets/skittles/rainbow.png",
  "name": "rainbow"
}, {
  "path": "/demos/assets/skittles/rainbow2.png",
  "name": "rainbow2"
}, {
  "path": "/demos/assets/skittles/bg1.png",
  "name": "bg"
}, {
  "path": "/demos/assets/skittles/anger.png",
  "name": "anger"
}, {
  "path": "/demos/assets/skittles/taste.png",
  "name": "taste"
}, {
  "path": "/demos/assets/skittles/stone.png",
  "name": "stone"
}, {
  "path": "/demos/assets/skittles/metal.png",
  "name": "metal"
}, {
  "path": "/demos/assets/skittles/angry_red.png",
  "name": "angry_red"
}, {
  "path": "/demos/assets/skittles/angry_black.png",
  "name": "angry_black"
}, {
  "path": "/demos/assets/skittles/angry_blue.png",
  "name": "angry_blue"
}, {
  "path": "/demos/assets/skittles/angry_yellow.png",
  "name": "angry_yellow"
}, {
  "path": "/demos/assets/skittles/angry_pigko.png",
  "name": "pig"
}, {
  "path": "/demos/assets/skittles/yellow2.png",
  "name": "yellow"
}, {
  "path": "/demos/assets/skittles/purple2.png",
  "name": "purple"
}, {
  "path": "/demos/assets/skittles/green2.png",
  "name": "green"
}, {
  "path": "/demos/assets/skittles/orange2.png",
  "name": "orange"
}, {
  "path": "/demos/assets/skittles/red2.png",
  "name": "red"
}];
